### PR TITLE
Hyperlink DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Same as https://github.com/SCOAP3/scoap3/pull/110 ;-)

### CODE REVIEW

**Comment by Dziolas** [comment]
Can you please rebase it on newest master branch? Thanks a lot.

**Comment by katrinleinweber** [comment]
That should be possible for you with a [merge option](https://help.github.com/articles/configuring-commit-rebasing-for-pull-requests/). If not, please let me know and I'll do it and force-push here.

**Comment by Dziolas** [comment]
There are conflicts so automatic rebase doesn't work. Would be easier for me if you could rebase and force-push. Thanks a lot.

**Comment by katrinleinweber** [comment]
Ah, OK. I incorrectly assumed that the conflicts only affect a normal merge, sorry.

**Comment by Dziolas** [comment]
No it's great. Thanks a lot.

**Pull request merged**
